In [25]:
import os
import pandas as pd

In [26]:
df_de_ln = pd.read_csv('../../results/02_10x_visium/03_de_analysis/de_results_LN_vs_Normal.csv', 
                       index_col=0)
df_de_src = pd.read_csv('../../results/02_10x_visium/03_de_analysis/de_results_SRC_vs_Normal.csv', 
                       index_col=0)

In [27]:
df_de_ln.head()

           baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
SAMD11   405.830407       -0.661058  0.381968 -1.730665  0.083512  0.146686
NOC2L    617.150593        0.099084  0.242832  0.408036  0.683247  0.765410
KLHL17   268.125145       -0.065161  0.219548 -0.296796  0.766622  0.829566
PLEKHN1  149.403538        0.191479  0.320693  0.597079  0.550455  0.650708
PERM1     64.753245       -1.710803  0.351668 -4.864827  0.000001  0.000024

In [28]:
df_de_src.head()

           baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
SAMD11   405.830407       -0.056660  0.368753 -0.153653  0.877884  0.929583
NOC2L    617.150593        0.181272  0.236296  0.767140  0.442998  0.615763
KLHL17   268.125145        0.022511  0.219502  0.102553  0.918318  0.953847
PLEKHN1  149.403538        0.890497  0.315607  2.821536  0.004779  0.026776
PERM1     64.753245       -0.819687  0.356462 -2.299506  0.021476  0.080331

In [29]:
in_dir = '../../manuscript/figures/main_fig1/upset_intersections'
out_dir = '../../results/02_10x_visium/08_sel_genes'

os.makedirs(out_dir, exist_ok=True)

In [30]:
df = pd.read_csv(f"{in_dir}/LN_down.csv", header=None)
df = df_de_ln.loc[df_de_ln.index.isin(df[0]), :]
df.to_csv(f"{out_dir}/LN_down.csv")

In [31]:
df = pd.read_csv(f"{in_dir}/LN_up.csv", header=None)
df = df_de_ln.loc[df_de_ln.index.isin(df[0]), :]
df.to_csv(f"{out_dir}/LN_up.csv")

In [32]:
df = pd.read_csv(f"{in_dir}/LN_up_SRC_down.csv", header=None)
df1 = df_de_ln.loc[df_de_ln.index.isin(df[0]), :]
df2 = df_de_src.loc[df_de_src.index.isin(df[0]), :]
df1['comparison'] = 'LN_up'
df2['comparison'] = 'SRC_down'
df = pd.concat([df1, df2], axis=0)
df.to_csv(f"{out_dir}/LN_up_SRC_down.csv")

/var/folders/rg/6bkp4j2s36nd_4x36jzgp1dm0000gn/T/ipykernel_32173/756333862.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['comparison'] = 'LN_up'
/var/folders/rg/6bkp4j2s36nd_4x36jzgp1dm0000gn/T/ipykernel_32173/756333862.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['comparison'] = 'SRC_down'

In [33]:
df = pd.read_csv(f"{in_dir}/SRC_down.csv", header=None)
df = df_de_src.loc[df_de_src.index.isin(df[0]), :]
df.to_csv(f"{out_dir}/SRC_down.csv")

In [34]:
df = pd.read_csv(f"{in_dir}/SRC_up.csv", header=None)
df = df_de_src.loc[df_de_src.index.isin(df[0]), :]
df.to_csv(f"{out_dir}/SRC_up.csv")

In [35]:
df = pd.read_csv(f"{in_dir}/SRC_down_LN_down.csv", header=None)
df1 = df_de_ln.loc[df_de_ln.index.isin(df[0]), :]
df2 = df_de_src.loc[df_de_src.index.isin(df[0]), :]
df1['comparison'] = 'LN_down'
df2['comparison'] = 'SRC_down'
df = pd.concat([df1, df2], axis=0)
df.to_csv(f"{out_dir}/SRC_down_LN_down.csv")

/var/folders/rg/6bkp4j2s36nd_4x36jzgp1dm0000gn/T/ipykernel_32173/2704815753.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['comparison'] = 'LN_down'
/var/folders/rg/6bkp4j2s36nd_4x36jzgp1dm0000gn/T/ipykernel_32173/2704815753.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['comparison'] = 'SRC_down'

In [36]:
df = pd.read_csv(f"{in_dir}/SRC_up_LN_up.csv", header=None)
df1 = df_de_ln.loc[df_de_ln.index.isin(df[0]), :]
df2 = df_de_src.loc[df_de_src.index.isin(df[0]), :]
df1['comparison'] = 'LN_up'
df2['comparison'] = 'SRC_up'
df = pd.concat([df1, df2], axis=0)
df.to_csv(f"{out_dir}/SRC_up_LN_up.csv")

/var/folders/rg/6bkp4j2s36nd_4x36jzgp1dm0000gn/T/ipykernel_32173/1194474633.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['comparison'] = 'LN_up'
/var/folders/rg/6bkp4j2s36nd_4x36jzgp1dm0000gn/T/ipykernel_32173/1194474633.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['comparison'] = 'SRC_up'